version: '3.8'

networks:
  broker-net:
    external: true

services:
  payment-service:
    image: payment-service:0.0.2
    container_name: paymentservice_app
    ports:
      - "8085:8080"
    environment:
      STRIPE_API_KEY: ${STRIPE_API_SECRET_KEY}
      SPRING_RABBITMQ_HOST: RabbitMQ       # <-- the container name of your existing broker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - broker-net
